### ISSUE TITLE
Multi item lib is not complete

### ISSUE THREAD

**Issue by Pyrix25633** [OroArmorModding/Multi-Item-Lib#11]
I'm trying to use this lib to make the bow like the vanilla one (that makes the zoom effect).
[Repo](https://github.com/Pyrix25633/Fabric-VanillaPlus) (Fabric 1.18.2, using multi item lib 1.5.2)
I've added
> maven {
		name = "OroArmor"
		url = "https://maven.oroarmor.com"
}

and
> include(modImplementation("com.oroarmor:multi-item-lib:1.5.2"))

to build.gradle and it builds fine, then I added
> UniqueItemRegistry.BOW.addItemToRegistry(ModItems.POWER_BOW);
UniqueItemRegistry.BOW.addItemToRegistry(ModItems.ELITE_POWER_BOW);

to both the client and server initializers (though I think only the client is needed, and I've tried also that) but It doesn't work, am I missing something?

**Comment by Pyrix25633** [comment]
Maybe this lib is only for proper rendering of the item, but doesn't add the zoom?

**Comment by Pyrix25633** [comment]
Well, I tried it with the crossbow and the change is significant, it works, so I guess there is no way to make them zoom?

**Comment by DaFuqs** [comment]
For bows and crossbows I wrote https://github.com/DaFuqs/Arrowhead/blob/master/src/main/java/de/dafuqs/arrowhead/api/ArrowheadBow.java once. Just include the lib & implement that interface on your bows. There also is a crossbow one.

**Comment by OroArmor** [comment]
The zoom is not part of this mod. As I slowly transition features from this to QuiltMC/quilt-standard-libraries, such as the bow stuff, i wont be going back to fix it
