### ISSUE TITLE
[1.3.2 on 1.17] Seems to crash, even with no other mods present.

### ISSUE THREAD

**Issue by AmyMialee** [OroArmorModding/Multi-Item-Lib#4]
[crash-2021-06-21_15.50.18-client.txt](https://github.com/OroArmor/Multi-Item-Lib/files/6687481/crash-2021-06-21_15.50.18-client.txt)

**Comment by Dillon8775** [comment]
this seemed to work for me
[ItemRendererMixin.txt](https://github.com/OroArmor/Multi-Item-Lib/files/6696156/ItemRendererMixin.txt)

**Comment by OroArmor** [comment]
fixed!
