### ISSUE TITLE
Crash involving HeldItemRendererMixin - @Redirect method for "renderFirstPersonItem" not working at all.

### ISSUE THREAD

**Issue by Dillon8775** [OroArmorModding/Multi-Item-Lib#5]
[crash-2021-07-15_13.59.32-client.txt](https://github.com/OroArmor/Multi-Item-Lib/files/6825339/crash-2021-07-15_13.59.32-client.txt)

@ Redirect(method = "renderFirstPersonItem", at = @At(value = "INVOKE", target = "Lnet/minecraft/item/ItemStack;isOf(Lnet/minecraft/item/Item;)Z", ordinal = 2))
    private boolean renderFirstPersonItem(ItemStack stack, Item isOfItem) {
        return UniqueItemRegistry.CROSSBOW.isItemInRegistry(stack.getItem());
    }

**Comment by OroArmor** [comment]
fixed!
