### ISSUE TITLE
Fishing Rods don't work on 1.4.0

### ISSUE THREAD

**Issue by AmyMialee** [OroArmorModding/Multi-Item-Lib#7]
Fishing Rods seem to not cast properly with the mod installed.

**Comment by OroArmor** [comment]
Could you elaborate on this?

**Comment by AmyMialee** [comment]
Still applies on 1.5.1.

When you use the fishing rod the bobber instantly despawns and resets the fishing rod.

**Comment by OroArmor** [comment]
fixed in 9a0f327
