### ISSUE TITLE
[1.4.0] Registered shields are not visible

### ISSUE THREAD

**Issue by Luligabi1** [OroArmorModding/Multi-Item-Lib#8]
Registered shields using the library remain invisible, while still working. Here are the [register code](https://github.com/Luligabi1/MagicFungi/blob/2970aa44131064d497fbc2d94d0cd845d824c001/src/main/java/me/luligabi/magicfungi/common/item/ItemRegistry.java#L32), [shield item](https://github.com/Luligabi1/MagicFungi/blob/2970aa44131064d497fbc2d94d0cd845d824c001/src/main/java/me/luligabi/magicfungi/common/item/ItemRegistry.java#L64) and [models](https://github.com/Luligabi1/MagicFungi/blob/development/src/main/resources/assets/magicfungi/models/item/clypeus_shield.json) (1:1 to vanilla's).

**Comment by OroArmor** [comment]
Check out https://github.com/OroArmor/Netherite-Plus-Mod for how to get shields rendering. This library only provides a way to get the shield to be functional.
